// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteReq struct {
	// Term is the new voting term.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Candidate is the candidate id
	CandidateId uint64 `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	// LastLogIndex is the last log index.
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	// LastLogTerm is the last log term.
	LastLogTerm          uint64   `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteReq) Reset()         { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()    {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *RequestVoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReq.Unmarshal(m, b)
}
func (m *RequestVoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReq.Marshal(b, m, deterministic)
}
func (m *RequestVoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReq.Merge(m, src)
}
func (m *RequestVoteReq) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReq.Size(m)
}
func (m *RequestVoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReq proto.InternalMessageInfo

func (m *RequestVoteReq) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReq) GetCandidateId() uint64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResp struct {
	// Term is the newer term if the lader is out of date.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Granted if the vote was granted.
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResp) Reset()         { *m = RequestVoteResp{} }
func (m *RequestVoteResp) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResp) ProtoMessage()    {}
func (*RequestVoteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *RequestVoteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResp.Unmarshal(m, b)
}
func (m *RequestVoteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResp.Marshal(b, m, deterministic)
}
func (m *RequestVoteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResp.Merge(m, src)
}
func (m *RequestVoteResp) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResp.Size(m)
}
func (m *RequestVoteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResp proto.InternalMessageInfo

func (m *RequestVoteResp) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResp) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*RequestVoteReq)(nil), "pb.RequestVoteReq")
	proto.RegisterType((*RequestVoteResp)(nil), "pb.RequestVoteResp")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xea, 0x61, 0xe4, 0xe2, 0x0b, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0xcb, 0x2f, 0x49, 0x0d, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0x29,
	0x49, 0x2d, 0xca, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x02, 0xb3, 0x85, 0x14, 0xb8, 0xb8,
	0x93, 0x13, 0xf3, 0x52, 0x32, 0x53, 0x12, 0x4b, 0x52, 0x3d, 0x53, 0x24, 0x98, 0xc0, 0x52, 0xc8,
	0x42, 0x42, 0x4a, 0x5c, 0x3c, 0x39, 0x89, 0xc5, 0x25, 0x3e, 0xf9, 0xe9, 0x9e, 0x79, 0x29, 0xa9,
	0x15, 0x12, 0xcc, 0x60, 0x25, 0x28, 0x62, 0x20, 0x53, 0xa0, 0xfc, 0x10, 0x90, 0x05, 0x2c, 0x10,
	0x53, 0x90, 0x84, 0x94, 0xdc, 0xb9, 0xf8, 0x51, 0x5c, 0x53, 0x5c, 0x80, 0xcb, 0x39, 0x65, 0xf9,
	0x25, 0xa9, 0xee, 0x45, 0x89, 0x79, 0x25, 0xa9, 0x10, 0xe7, 0x70, 0x04, 0x21, 0x0b, 0x19, 0xb9,
	0x73, 0x71, 0x07, 0x25, 0xa6, 0x95, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x59, 0x70,
	0x71, 0x23, 0x99, 0x2b, 0x24, 0xa4, 0x57, 0x90, 0xa4, 0x87, 0xea, 0x6d, 0x29, 0x61, 0x0c, 0xb1,
	0xe2, 0x02, 0x25, 0x86, 0x24, 0x36, 0x70, 0x58, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2b,
	0x41, 0xee, 0x72, 0x37, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RaftServiceClient is the client API for RaftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftServiceClient interface {
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResp, error)
}

type raftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftServiceClient(cc grpc.ClientConnInterface) RaftServiceClient {
	return &raftServiceClient{cc}
}

func (c *raftServiceClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResp, error) {
	out := new(RequestVoteResp)
	err := c.cc.Invoke(ctx, "/pb.RaftService/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServiceServer is the server API for RaftService service.
type RaftServiceServer interface {
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteResp, error)
}

// UnimplementedRaftServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServiceServer struct {
}

func (*UnimplementedRaftServiceServer) RequestVote(ctx context.Context, req *RequestVoteReq) (*RequestVoteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}

func RegisterRaftServiceServer(s *grpc.Server, srv RaftServiceServer) {
	s.RegisterService(&_RaftService_serviceDesc, srv)
}

func _RaftService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RaftService/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RaftService",
	HandlerType: (*RaftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
